services:
  harisco-portal:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - harisco_data:/app/server/prisma
      - harisco_backups:/app/server/backups
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=harisco_super_secret_prod_key
    restart: unless-stopped

volumes:
  harisco_data:
  harisco_backups:
